### ISSUE TITLE
Why is the dataset loading abnormally slow

### ISSUE THREAD

**Issue by fengzi1013** [wzhouad/Contra-OOD#1]
Why is the dataset loading abnormally slow,

**Comment by wzhouad** [comment]
The datasets are downloaded using [Huggingface's datasets](https://github.com/huggingface/datasets). You can create an issue there.

**Comment by fengzi1013** [comment]
Thank you for your reply, but when I downloaded the datasets, I also felt slow when loading it locally, such as multi30K

**Comment by Gy915** [comment]
Turn on your VPN
