### ISSUE TITLE
Problem of Table 2

### ISSUE THREAD

**Issue by wjczf123** [wzhouad/Contra-OOD#2]
The Table 2 seems confused. Why L_{margin} + MSP are not in green on SST2 dataset and in green on IMDb dataset?
You write 'Results where the contrastive loss improves OOD detection on both evaluation metrics are highlighted in green.' And lower FAR95 is better.

**Comment by wzhouad** [comment]
The SST2 cell should be in green, and the IMDB cell shouldn't. Thank you for pointing this out.

**Comment by wjczf123** [comment]
OK. Thank you for your reply.
