### ISSUE TITLE
关于loss的一点疑问？

### ISSUE THREAD

**Issue by topDreamer** [wzhouad/Contra-OOD#4]
非常好的工作！
请问一下论文中实现的Supervised Contrastive Learning Loss https://github.com/wzhouad/Contra-OOD/blob/2a1d63a61c8b03efdc27ca08b22f5fab2bc6001d/model.py#L46 和 原论文中提供的SCL代码https://github.com/HobbitLong/SupContrast/blob/master/losses.py有什么差异吗？
看起来本文实现的更为简洁？

**Comment by wzhouad** [comment]
除了temperature的值不一样，其他的都相同
